name: around_you
description: Premium iOS AR social discovery app where users create, share, and discover memories anchored to real-world locations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
    
  # State Management
  provider: ^6.1.1
  
  # UI & Animations
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Network & Data
  http: ^1.1.0
  dio: ^5.3.2
  cached_network_image: ^3.3.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Device Features
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  geolocator: ^9.0.2
  permission_handler: ^10.1.0
  device_info_plus: ^9.1.0
  sensors_plus: ^4.0.2
  
  # Firebase (Backend)
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  firebase_messaging: ^14.7.0
  firebase_analytics: ^10.7.0
  firebase_crashlytics: ^3.4.0
  
  # Authentication
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  
  # Audio/Video
  just_audio: ^0.9.36
  video_player: ^2.8.1
  record: ^5.0.4
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.1.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  package_info_plus: ^4.2.0
  
  # AR & Camera
  ar_flutter_plugin: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Linting & Analysis
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.5
  patrol: ^3.19.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/fonts/
    
  # Fonts
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.otf
          weight: 700
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SFProText-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProText-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProText-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFProText-Bold.otf
          weight: 700

# Flutter configuration
flutter_native_splash:
  color: "#0A0A0F"
  image: assets/images/splash_logo.png
  color_dark: "#F8F7FF"
  image_dark: assets/images/splash_logo_dark.png
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#6B1FB3"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"